version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=your-secure-password"
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  openlibrary-app:
    build: .
    container_name: openlibrary-app
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - "SPRING_ELASTICSEARCH_URIS=elasticsearch:9200"
      - "SPRING_ELASTICSEARCH_USERNAME=elastic"
      - "SPRING_ELASTICSEARCH_PASSWORD=your-secure-password"
      - "APP_DATA_FOLDER=/data"
      - "APP_SOCKET_TIMEOUT=60"
      - "APP_CONNECTION_TIMEOUT=60"
    volumes:
      - ./data:/data
    depends_on:
      - elasticsearch

volumes:
  elastic_data:
    driver: local
